#pragma once

typedef enum ResourceID
{
    RES_MODEL_PLAYER,
    RES_MODEL_ZOMBIE,
    RES_MODEL_DEVIL,
    RES_MODEL_MUMMY,
    RES_MODEL_TANK,
    RES_MODEL_BARREL,
    RES_MODEL_CRATE,
    RES_MODEL_TURRET,
    RES_TEX_CROSSHAIR,
    RES_SHADER_CEL,
    RES_SND_PISTOL,
    RES_SND_EXPLOSION,
    RES_FONT_UI,
    RES_COUNT
} ResourceID;

typedef enum ResourceType
{
    RESTYPE_MODEL,
    RESTYPE_TEXTURE,
    RESTYPE_SHADER,
    RESTYPE_SOUND,
    RESTYPE_FONT,
} ResourceType;
